// Code generated by entc, DO NOT EDIT.

package userinfo

const (
	// Label holds the string label denoting the userinfo type in the database.
	Label = "user_info"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserIdentity holds the string denoting the user_identity field in the database.
	FieldUserIdentity = "user_identity"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldForm holds the string denoting the form field in the database.
	FieldForm = "form"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"

	// Table holds the table name of the userinfo in the database.
	Table = "user_info"
)

// Columns holds all SQL columns for userinfo fields.
var Columns = []string{
	FieldID,
	FieldUserIdentity,
	FieldChannel,
	FieldForm,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultChannel holds the default value on creation for the channel field.
	DefaultChannel int32
	// DefaultForm holds the default value on creation for the form field.
	DefaultForm int32
)
