// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// MiniProgramAccount is the predicate function for miniprogramaccount builders.
type MiniProgramAccount func(*sql.Selector)

// PhoneAccount is the predicate function for phoneaccount builders.
type PhoneAccount func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserAccount is the predicate function for useraccount builders.
type UserAccount func(*sql.Selector)

// UserExtend is the predicate function for userextend builders.
type UserExtend func(*sql.Selector)

// UserInfo is the predicate function for userinfo builders.
type UserInfo func(*sql.Selector)
