// Code generated by entc, DO NOT EDIT.

package miniprogramaccount

const (
	// Label holds the string label denoting the miniprogramaccount type in the database.
	Label = "mini_program_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserIdentity holds the string denoting the user_identity field in the database.
	FieldUserIdentity = "user_identity"
	// FieldOpenID holds the string denoting the open_id field in the database.
	FieldOpenID = "open_id"
	// FieldNickName holds the string denoting the nick_name field in the database.
	FieldNickName = "nick_name"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldProvince holds the string denoting the province field in the database.
	FieldProvince = "province"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"

	// Table holds the table name of the miniprogramaccount in the database.
	Table = "mini_program_account"
)

// Columns holds all SQL columns for miniprogramaccount fields.
var Columns = []string{
	FieldID,
	FieldUserIdentity,
	FieldOpenID,
	FieldNickName,
	FieldAvatarURL,
	FieldGender,
	FieldCountry,
	FieldProvince,
	FieldCity,
	FieldLanguage,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNickName holds the default value on creation for the nick_name field.
	DefaultNickName string
	// DefaultAvatarURL holds the default value on creation for the avatar_url field.
	DefaultAvatarURL string
	// DefaultGender holds the default value on creation for the gender field.
	DefaultGender int32
	// DefaultCountry holds the default value on creation for the country field.
	DefaultCountry string
	// DefaultProvince holds the default value on creation for the province field.
	DefaultProvince string
	// DefaultCity holds the default value on creation for the city field.
	DefaultCity string
	// DefaultLanguage holds the default value on creation for the language field.
	DefaultLanguage string
)
